name: CI - Build and Test

on:
  push:
    branches-ignore:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint --if-present
        continue-on-error: true

      - name: Run type check
        run: npx tsc --noEmit

      - name: Build
        run: npm run build
        env:
          # Use placeholder values for CI builds
          VITE_FIREBASE_API_KEY: 'ci-placeholder'
          VITE_FIREBASE_AUTH_DOMAIN: 'ci-placeholder.firebaseapp.com'
          VITE_FIREBASE_PROJECT_ID: 'ci-placeholder'
          VITE_FIREBASE_STORAGE_BUCKET: 'ci-placeholder.appspot.com'
          VITE_FIREBASE_MESSAGING_SENDER_ID: '000000000000'
          VITE_FIREBASE_APP_ID: '1:000000000000:web:placeholder'
          VITE_GA_MEASUREMENT_ID: 'G-PLACEHOLDER'

      - name: Check bundle size
        run: |
          BUNDLE_SIZE=$(find dist -name "*.js" -exec wc -c {} + | awk '{sum+=$1} END {print sum}')
          echo "📦 Bundle size: $BUNDLE_SIZE bytes"
          # Alert if bundle is larger than 1MB
          if [ $BUNDLE_SIZE -gt 1048576 ]; then
            echo "⚠️ Warning: Bundle size exceeds 1MB"
          fi

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
          retention-days: 7
